--DROP TABLE TB_TAREFAS;
--DROP SEQUENCE SQ_TAREFAS;

CREATE TABLE TB_TAREFAS(
	ID NUMBER NOT NULL PRIMARY KEY,
	DESCRICAO VARCHAR2(100) NOT NULL,
	DATA_LIMITE DATE NOT NULL,
	FEITA NUMBER(1) DEFAULT 0
);

CREATE SEQUENCE SQ_TAREFAS INCREMENT BY 1 START WITH 1  NOCYCLE ORDER;

INSERT INTO TB_TAREFAS(ID, DESCRICAO, DATA_LIMITE) VALUES (SQ_TAREFAS.NEXTVAL, 'Fazer compras',
	TO_DATE('21/08/2020', 'dd/mm;yyyy'));
INSERT INTO TB_TAREFAS(ID, DESCRICAO, DATA_LIMITE) VALUES (SQ_TAREFAS.NEXTVAL, 'Caminhar',
	TO_DATE('21/08/2020', 'dd/mm;yyyy'));
INSERT INTO TB_TAREFAS(ID, DESCRICAO, DATA_LIMITE) VALUES (SQ_TAREFAS.NEXTVAL, 'Fazer Café',
	TO_DATE('21/08/2020', 'dd/mm;yyyy'));
INSERT INTO TB_TAREFAS(ID, DESCRICAO, DATA_LIMITE) VALUES (SQ_TAREFAS.NEXTVAL, 'Estudar JAVA e Oracle',
	TO_DATE('21/08/2020', 'dd/mm;yyyy'));
	
SELECT * FROM TB_TAREFAS